
language: java

before_install:
  - curl https://vdt.cs.wisc.edu/upstream/gums/1.3.18.009/openws-1.2.2.jar > openws-1.2.2.jar
  - mvn install:install-file -B -DgroupId=org.opensaml -DartifactId=openws -Dversion=1.2.2 -Dpackaging=jar -Dfile=openws-1.2.2.jar
  - curl http://t2.unl.edu/store/sources/voms-api-java.jar > voms-api-java.jar
  - mvn install:install-file -B -DgroupId=org.italiangrid -DartifactId=voms-api-java -Dversion=2.0.8 -Dpackaging=jar -Dfile=voms-api-java.jar
  - curl http://t2.unl.edu/store/sources/trustmanager.jar > trustmanager.jar
  - mvn install:install-file -B -DgroupId=emi -DartifactId=emi-trustmanager -Dversion=3.0.3 -Dpackaging=jar -Dfile=trustmanager.jar

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

